/*
 * SpoonacularAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/19/2017
 */
using System;
using SpoonacularAPI.PCL.Controllers;
using SpoonacularAPI.PCL.Http.Client;

namespace SpoonacularAPI.PCL
{
    public partial class SpoonacularAPIClient
    {

        /// <summary>
        /// Singleton access to Client controller
        /// </summary>
        public APIController Client
        {
            get
            {
                return APIController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public SpoonacularAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public SpoonacularAPIClient(string xMashapeKey)
        {
            Configuration.XMashapeKey = xMashapeKey;
        }
    }
}