/*
 * SpoonacularAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/19/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SpoonacularAPI.PCL;
using SpoonacularAPI.PCL.Utilities;

namespace SpoonacularAPI.PCL.Models
{
    public class Classifiedproduct : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private List<string> breadcrumbs;
        private string category;
        private string cleanTitle;
        private int usdaCode;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("breadcrumbs")]
        public List<string> Breadcrumbs 
        { 
            get 
            {
                return this.breadcrumbs; 
            } 
            set 
            {
                this.breadcrumbs = value;
                onPropertyChanged("Breadcrumbs");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("category")]
        public string Category 
        { 
            get 
            {
                return this.category; 
            } 
            set 
            {
                this.category = value;
                onPropertyChanged("Category");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cleanTitle")]
        public string CleanTitle 
        { 
            get 
            {
                return this.cleanTitle; 
            } 
            set 
            {
                this.cleanTitle = value;
                onPropertyChanged("CleanTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("usdaCode")]
        public int UsdaCode 
        { 
            get 
            {
                return this.usdaCode; 
            } 
            set 
            {
                this.usdaCode = value;
                onPropertyChanged("UsdaCode");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 