/*
 * SpoonacularAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/19/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SpoonacularAPI.PCL;
using SpoonacularAPI.PCL.Utilities;

namespace SpoonacularAPI.PCL.Models
{
    public class FindByIngredientsModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int id;
        private string image;
        private int likes;
        private int missedIngredientCount;
        private string title;
        private int usedIngredientCount;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("image")]
        public string Image 
        { 
            get 
            {
                return this.image; 
            } 
            set 
            {
                this.image = value;
                onPropertyChanged("Image");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("likes")]
        public int Likes 
        { 
            get 
            {
                return this.likes; 
            } 
            set 
            {
                this.likes = value;
                onPropertyChanged("Likes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("missedIngredientCount")]
        public int MissedIngredientCount 
        { 
            get 
            {
                return this.missedIngredientCount; 
            } 
            set 
            {
                this.missedIngredientCount = value;
                onPropertyChanged("MissedIngredientCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("usedIngredientCount")]
        public int UsedIngredientCount 
        { 
            get 
            {
                return this.usedIngredientCount; 
            } 
            set 
            {
                this.usedIngredientCount = value;
                onPropertyChanged("UsedIngredientCount");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 